error = 5
flag = "white"
monHipHop = 6 + error
tuesRock = 45 + error
knockColor = 1
wedWayBack = 42 + error
thursThrowback = 35 + error
fridayHits = 53 + error
satDisco = 3 + error
sunCountry = 55 + error
holiday = 51 + error
yacht = 10 + error
michealJ = 31 + error
numSongs = 4
numStations = 10
arduinoNum = '0'
globalDelay = 0.077
path = "/Users/s1034274/Desktop"
#path = "/home/pi/Desktop"
